### ISSUE TITLE
Streamline frontend refresh network calls 🛠🛠🛠

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#300]
When the user refreshes the frontend, it makes ~10 API calls to the backend to set up stuff like what model is being used, what state the phases are in, retrieving chat, email, and defences etc. Can we make this one call, where the frontend asks about the current state of the app when the frontend is refreshed. 

<hr>

Here's what happens if I refresh on level 1:

- `health/` always returns with 200 (if the backend is up).
- `email/get?level=0` returns all the sent emails in the session for given level.
- `openai/history?level=0` returns the chat history in the session for given level.
- `defence/status?level=0` returns the defences as configured for given level.
- `openai/validModels` returns all the available models from openAI for the api key configured in the backend.
- `systemRoles/` returns the default system role values for levels 1, 2 and 3.

If we refresh on sandbox we get an additional 4 calls to `openai/model`, all of which return the currently selected model and its config values.

🔧 These should be combined.
🔧 Stop the additional calls to `openai/model` on sandbox.

# AC:

GIVEN frontend in preview mode (so that react doesn't do its double render thing) `npm run preview`
WHEN the user refreshes the website on any level
THEN there should be only one api call made of type fetch

Here's how you quickly find out what api calls are being made that are fetch type. Note that the CombinedFonts call is of type xhr, therefore we ignore it.

![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/48b15e2b-5cbe-4e1c-9495-8848d400c03c)

**Comment by pmarsh-scottlogic** [comment]
investigated under #792 

Here's what happens if I refresh on level 1:
- `health/` always returns with 200 (if the backend is up).
- `email/get?level=0` returns all the sent emails in the session for given level.
- `openai/history?level=0` returns the chat history in the session for given level.
- `defence/status?level=0` returns the defences as configured for given level.
- `openai/validModels` returns all the available models from openAI for the api key configured in the backend.
- `systemRoles/` returns the default system role values for levels 1, 2 and 3.

**Comment by pmarsh-scottlogic** [comment]
- add a GET levelState endpoint which returns
  - emails
  - chat history
  - configured defences
- Remove all calls and related code to the health endpoint from the frontend.
