### ISSUE TITLE
Python tool call not supported

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [ScottLogic/prompt-injection#687]
# Bug report

## Description

I've managed to create a tool call "python" with the prompt. `come up with 10 new email addresses. then for each of those new email addresses, send an email to it wishing a merry christmas`. My guess is that because it involves a "loop" it starts this tool call which we don't support. Maybe we should support that?

Once this has occured, all subsequent messages see an error.

## Reproduction steps
- Load up the app
- send the prompt `come up with 10 new email addresses. then for each of those new email addresses, send an email to it wishing a merry christmas`
- observe the error
- send any further messages
- observe errors on those

## Expected behaviour
It should come up with a sensible response. Or, at least, it should let you know why it failed to get a reply! Then it should recover and be able to deal with further messages.

## Screenshots

![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/2023a74f-f9a4-46f4-b7d6-3271334f31de)

### initial error
```
Server is running on port 3001
No defences applied. Message unchanged.
{"blockedReason":null,"isBlocked":false,"alertedDefences":[],"triggeredDefences":[]}
User message: 'come up with 10 new email addresses. then for each of those new email addresses, send an email to it wishing a merry christmas'
Talking to model:  {"id":"gpt-3.5-turbo","configuration":{"temperature":1,"topP":1,"frequencyPenalty":0,"presencePenalty":0}}
Calling OpenAI chat completion...
OpenAI chat completion took 3457ms
Unknown function: python
Talking to model:  {"id":"gpt-3.5-turbo","configuration":{"temperature":1,"topP":1,"frequencyPenalty":0,"presencePenalty":0}}
Calling OpenAI chat completion...
Error calling createChatCompletion:  400 An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_FlHgGZh8VjoP2nboCqeZW3Na
OpenAI chat completion took 432ms
Error: Failed to get chatGPT reply
    at handleChatToGPT (c:\dev\SL Projects\prompt-injection\backend\src\controller\chatController.ts:199:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Failed to get chatGPT reply
```

### Subsequent errors (on further messages)
```
User message: 'hello'
Talking to model:  {"id":"gpt-3.5-turbo","configuration":{"temperature":1,"topP":1,"frequencyPenalty":0,"presencePenalty":0}}
Calling OpenAI chat completion...
Error calling createChatCompletion:  400 An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_FlHgGZh8VjoP2nboCqeZW3Na
OpenAI chat completion took 233ms
Error: Failed to get chatGPT reply
    at handleChatToGPT (c:\dev\SL Projects\prompt-injection\backend\src\controller\chatController.ts:199:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Failed to get chatGPT reply
```

## Software (please complete the following information):

- Browser: chrome. But reproduces via postman request too.

## Acceptance criteria

**GIVEN** some setup
**WHEN** an action happens
**THEN** the expected outcome

** TBD **

**Comment by pmarsh-scottlogic** [comment]
Question: How do we want to handle this situation?

**Comment by heatherlogan-scottlogic** [comment]
**First issue - why is it calling a python function?** 

On the above prompt the model generates input for a function:
` function: {name: 'python', arguments: 'arguments:
'import random\nimport string\n\ndef generate_email_address():\n    letters = string.ascii_lowercase\n    username = ''.join(random.choice(letters) for i in range(10))\n    domain = ''.join(random.choice(letters) for i in range(5))\n    extension = ''.join(random.choice(letters) for i in range(3))\n    return f"{username}@{domain}.{extension}"\n\nemail_addresses = []\nfor _ in range(10):\n    email_addresses.append(generate_email_address())\n\nemail_addresses'
name:
'python''}
id: 'call_h36FxW2RluT4bHa0REdBcQwi' type: 'function'}
`
I'm putting this down to a weird GPT quirk, sometimes it will calculate codey questions fine but in this case it's assuming a function call for a python script 🤔 IDK and don't think it's anything to do with our code.. 

**Second issue - unable to chat after initial error **

Because there was a failure mid tool call, an assistant calls the initial tool (with some tool_call_id) and adds this to the chat history, then there is not a reply from the tool with with the same corresponding tool_call_id added to the chat history. This gives the following error when this "broken" chat history is fed to model:  
`Error calling createChatCompletion:  400 An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_6ktDzzbMuUvSOcCqMF8HuUXn`

To fix we can handle errors occurring inside the tool call function so that if there is a failure, a response is still output with the corresponding tool_call_id, so there should not be a case where there isn't matching tool_call_ids present in the chat history.
