### ISSUE TITLE
`getOpenAIKey` should be a function declaration

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [ScottLogic/prompt-injection#711]
We got this rather quirky definition here.
```typescript
const getOpenAIKey = (() => {
	let openAIKey: string | undefined = undefined;
	return () => {
		if (!openAIKey) {
			openAIKey = process.env.OPENAI_API_KEY;
			if (!openAIKey) {
				throw new Error(
					'OpenAI API key not found in environment vars - cannot continue!'
				);
			}
		}
		return openAIKey;
	};
})();
```
I can't quite tell what's going on here with all the anonymous methods! But I'm pretty sure all we need is

```typescript
function getOpenAIKey() {
	const openAIKey = process.env.OPENAI_API_KEY;
	if (!openAIKey) {
		throw new Error(
			'OpenAI API key not found in environment vars - cannot continue!'
		);
	}
	return openAIKey;
};
```

**Comment by chriswilty** [comment]
@pmarsh-scottlogic They do different things. The current implementation is a pretty standard "lazy initialisation" where we only look up the value once, store it in a closure, and then just return that value on all subsequent invocations. This we can do because it's an environment variable that won't change. It's more efficient than looking it up every time.

It also means that, because we quit the server on startup if we cannot find the key, we are guaranteed to have the key on all subsequent calls if the server did start successfully, so we don't need to worry about an error being thrown once the application is up and running.

**Comment by pmarsh-scottlogic** [comment]
Thanks for explaining @chriswilty!
